### ISSUE TITLE
Vagrant is missing orlo in path, and broken python path

### ISSUE THREAD

**Issue by Alrocky** [eBayClassifiedsGroup/orlo#32]
`python setup.py install`
is not installing orlo in default `/usr/local/bin` path.

and moreover  it exists only in vagrant directory and is totally broken:

```
root@vagrant-ubuntu-trusty-64:/vagrant# cat bin/orlo
#!/bin/bash
/usr/share/python/orlo/bin/python /usr/share/python/orlo/lib/python2.7/site-packages/orlo/cli.py $@
```

```
which python
/usr/bin/python
```

ps.
How about creating docker images that will start like `docker run` with  ENV variable for  postgres / mysql /  sqlite setup

**Comment by al4** [comment]
Yep you're right. The reason is that I've been deploying Orlo with Debian packages and not with pip - essentially the setup.py exists for testing and building the package. This is not how it should be though, I certainly want a pip install to be possible, so I'll look at fixing this up, most likely next week. A pull request is most welcome if you can get to it before I can.

A docker image is also a great idea.

Cheers!

**Comment by al4** [comment]
Closed this by commit without explanation. :-)

I've added an entry point to setup.py, which will install an "orlo" command to /usr/local/bin when you do pip install. The script in <project root>/bin (the debian script) has been moved to the debian directory in a separate commit.
